/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KTGK_CS311AU_2324_NguyenHuuHoang_6536;

import static KTGK_CS311AU_2324_NguyenHuuHoang_6536.DanhMucSach.danhSachSach;
import static KTGK_CS311AU_2324_NguyenHuuHoang_6536.DanhMucSach.docDanhSachSach;
import static KTGK_CS311AU_2324_NguyenHuuHoang_6536.DanhMucSach.luuDanhSachSach;

import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAIP
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void themsach() {
        if (btnSachGiaoKhoa.isSelected()) {
            SachGiaoKhoa giaoKhoa = new SachGiaoKhoa();
            giaoKhoa.tenSach = txtTenSach.getText();
            giaoKhoa.nhaXuatBan = txtNhaXuatBan.getText();
            giaoKhoa.giaBan = Integer.parseInt(txtGiaBan.getText());
            giaoKhoa.namXuatBan = Integer.parseInt(txtNamXuatBan.getText());
            giaoKhoa.soLuong = Integer.parseInt(txtSoLuong.getText());
            giaoKhoa.soTrang = Integer.parseInt(txtSoTrang.getText());
            danhSachSach.add(giaoKhoa);
            fillTable();
        } else {
            TieuThuyet tieuThuyet = new TieuThuyet();
            tieuThuyet.tenSach = txtTenSach.getText();
            tieuThuyet.nhaXuatBan = txtNhaXuatBan.getText();
            tieuThuyet.giaBan = Integer.parseInt(txtGiaBan.getText());
            tieuThuyet.namXuatBan = Integer.parseInt(txtNamXuatBan.getText());
            tieuThuyet.soLuong = Integer.parseInt(txtSoLuong.getText());
            tieuThuyet.soTrang = Integer.parseInt(txtSoTrang.getText());
            danhSachSach.add(tieuThuyet);
            fillTable();
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);

        for (DanhMuc danhMuc : danhSachSach) {
            if (danhMuc instanceof SachGiaoKhoa) {
                model.addRow(new Object[]{
                    ((SachGiaoKhoa) danhMuc).tenSach,
                    ((SachGiaoKhoa) danhMuc).nhaXuatBan,
                    ((SachGiaoKhoa) danhMuc).namXuatBan,
                    ((SachGiaoKhoa) danhMuc).soTrang,
                    ((SachGiaoKhoa) danhMuc).soLuong,
                    ((SachGiaoKhoa) danhMuc).giaBan,
                    danhMuc.thanhTien()
                });

            } else {
                model.addRow(new Object[]{
                    ((TieuThuyet) danhMuc).tenSach,
                    ((TieuThuyet) danhMuc).nhaXuatBan,
                    ((TieuThuyet) danhMuc).namXuatBan,
                    ((TieuThuyet) danhMuc).soTrang,
                    ((TieuThuyet) danhMuc).soLuong,
                    ((TieuThuyet) danhMuc).giaBan,
                    danhMuc.thanhTien()
                });
            }
        }
    }

    public void timSachCoThanhTienLonNhat() {
        DanhMuc sachCoThanhTienLonNhat = null;
        double maxThanhTien = Double.MIN_VALUE; // Khởi tạo giá trị lớn nhất ban đầu

        for (DanhMuc danhMuc : danhSachSach) {
            double thanhTien = danhMuc.thanhTien(); // Tính toán thành tiền

            if (thanhTien > maxThanhTien) {
                maxThanhTien = thanhTien; // Cập nhật giá trị lớn nhất
                sachCoThanhTienLonNhat = danhMuc; // Lưu lại cuốn sách có thành tiền lớn nhất
            }
        }

        if (sachCoThanhTienLonNhat != null) {
            JOptionPane.showMessageDialog(this, "Sách có thành tiền lớn nhất là: " + sachCoThanhTienLonNhat.tenSach + " với thành tiền là: " + maxThanhTien);
            // In ra thông tin của cuốn sách có thành tiền lớn nhất
        } else {
            System.out.println("Không tìm thấy sách nào trong danh sách.");
        }
    }

    public void sapXepTangDanTheoThanhTien() {
        // Sử dụng phương thức sort của lớp Collections để sắp xếp danh sách dms theo thành tiền tăng dần
        Collections.sort(danhSachSach, (sach1, sach2) -> Double.compare(sach1.thanhTien(), sach2.thanhTien()));
        // Gọi lại phương thức fillTable để cập nhật bảng hiển thị
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSach = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamXuatBan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNhaXuatBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoTrang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnSachGiaoKhoa = new javax.swing.JRadioButton();
        btnSachTieuThuyet = new javax.swing.JRadioButton();
        btnThemSach = new javax.swing.JButton();
        btnXoaSach = new javax.swing.JButton();
        btnDocSach = new javax.swing.JButton();
        btnLuuSach = new javax.swing.JButton();
        btnTimSachCoThanTienLonNhat = new javax.swing.JButton();
        BtnSapXepTangDanTheoThanhTien = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lí Sách");

        jLabel2.setText("Tên sách");

        txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSachActionPerformed(evt);
            }
        });

        jLabel3.setText("Năm Xuất Bản");

        txtNamXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamXuatBanActionPerformed(evt);
            }
        });

        jLabel4.setText("Giá Bán");

        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });

        jLabel5.setText("Nhà Xuất Bản");

        txtNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhaXuatBanActionPerformed(evt);
            }
        });

        jLabel6.setText("Số Trang");

        txtSoTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTrangActionPerformed(evt);
            }
        });

        jLabel7.setText("Số Lượng");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        buttonGroupSach.add(btnSachGiaoKhoa);
        btnSachGiaoKhoa.setSelected(true);
        btnSachGiaoKhoa.setText("Sách Giáo Khoa");

        buttonGroupSach.add(btnSachTieuThuyet);
        btnSachTieuThuyet.setText("Sách Tiểu Thuyết");

        btnThemSach.setText("Thêm sách");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        btnXoaSach.setText("Xóa Sách");
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });

        btnDocSach.setText("Đọc Sách");
        btnDocSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocSachActionPerformed(evt);
            }
        });

        btnLuuSach.setText("Lưu Sách");
        btnLuuSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuSachMouseClicked(evt);
            }
        });

        btnTimSachCoThanTienLonNhat.setText("Tìm Sách Có Giá Thành Tiền Lớn Nhất");
        btnTimSachCoThanTienLonNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSachCoThanTienLonNhatActionPerformed(evt);
            }
        });

        BtnSapXepTangDanTheoThanhTien.setText("Sắp Xếp");
        BtnSapXepTangDanTheoThanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSapXepTangDanTheoThanhTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSach)
                            .addComponent(txtNamXuatBan)
                            .addComponent(txtGiaBan)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnSachGiaoKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhaXuatBan)
                            .addComponent(txtSoTrang)
                            .addComponent(txtSoLuong)
                            .addComponent(btnSachTieuThuyet, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addGap(257, 257, 257))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThemSach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoaSach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDocSach))
                            .addComponent(btnTimSachCoThanTienLonNhat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnSapXepTangDanTheoThanhTien)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLuuSach)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSachGiaoKhoa)
                    .addComponent(btnSachTieuThuyet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSach)
                    .addComponent(btnXoaSach)
                    .addComponent(btnDocSach)
                    .addComponent(btnLuuSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimSachCoThanTienLonNhat)
                    .addComponent(BtnSapXepTangDanTheoThanhTien))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sách", "Nhà Xuất Bản", "Năm Xuất Bản", "Số Trang", "Số Lượng", "Giá Bán", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSach);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachActionPerformed

    private void txtNamXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamXuatBanActionPerformed

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void txtNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhaXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhaXuatBanActionPerformed

    private void txtSoTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTrangActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        themsach();
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnDocSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocSachActionPerformed
        danhSachSach = (List<DanhMuc>) docDanhSachSach("danhmucsach.dat");
        fillTable();
        JOptionPane.showMessageDialog(this, "Mở Sách Thành công đường Dẫn danhmucsach.dat ");
    }//GEN-LAST:event_btnDocSachActionPerformed

    private void btnLuuSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuSachMouseClicked
        luuDanhSachSach(danhSachSach, "danhmucsach.dat");
        fillTable();
        JOptionPane.showMessageDialog(this, "Lưu sách thành công vào đường Dẫn danhmucsach.dat ");
    }//GEN-LAST:event_btnLuuSachMouseClicked

    private void btnTimSachCoThanTienLonNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSachCoThanTienLonNhatActionPerformed
        timSachCoThanhTienLonNhat();
    }//GEN-LAST:event_btnTimSachCoThanTienLonNhatActionPerformed

    private void BtnSapXepTangDanTheoThanhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSapXepTangDanTheoThanhTienActionPerformed
        sapXepTangDanTheoThanhTien();
    }//GEN-LAST:event_BtnSapXepTangDanTheoThanhTienActionPerformed

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        int i = tblSach.getSelectedRow();
        if (i > -1) {
            danhSachSach.remove(i);
            fillTable();
        } else {
            JOptionPane.showMessageDialog(this, "Vui Lòng chọn hàng sách để xóa");
        }
    }//GEN-LAST:event_btnXoaSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSapXepTangDanTheoThanhTien;
    private javax.swing.JButton btnDocSach;
    private javax.swing.JButton btnLuuSach;
    private javax.swing.JRadioButton btnSachGiaoKhoa;
    private javax.swing.JRadioButton btnSachTieuThuyet;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnTimSachCoThanTienLonNhat;
    private javax.swing.JButton btnXoaSach;
    private javax.swing.ButtonGroup buttonGroupSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
